# Generated by Django 4.2.27 on 2025-12-15 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogging_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='bike_choice',
            field=models.IntegerField(choices=[(0, 'Hardtail'), (1, 'Full Suspension'), (2, 'Road Bike'), (3, 'Hybrid Bike'), (4, 'Electric Bike'), (5, 'Gravel Bike')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogging_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.IntegerField(choices=[(0, 'Sunny'), (1, 'Overcast'), (2, 'Rainy'), (3, 'Snowy'), (4, 'Windy'), (5, 'Foggy')], default=0),
        ),
    ]
