# Generated by Django 4.2.27 on 2025-12-22 22:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.IntegerField(choices=[('KAW', 'King Alfreds Way'), ('GNT', 'Great North Trail'), ('MCW', 'Marcher Castles Way'), ('TE', 'Traws Eryri'), ('NDW', 'North Downs Way'), ('RW', 'Rebellion Way'), ('WKW', 'West Kernow Way'), ('OTHER', 'Other')], default=0),
        ),
    ]
