# Generated by Django 4.2.27 on 2025-12-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_alter_post_image_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('KAW', 'King Alfreds Way'), ('GNT', 'Great North Trail'), ('MCW', 'Marcher Castles Way'), ('TE', 'Traws Eryri'), ('NDW', 'North Downs Way'), ('RW', 'Rebellion Way'), ('WKW', 'West Kernow Way'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
