# Generated by Django 4.2.27 on 2025-12-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', help_text='A short summary of the post', max_length=300),
            preserve_default=False,
        ),
    ]
